title: "Everything that Moves & Thinks"
tagline: "What happens when robots get a language interface"
description: "I'm a robotics engineer exploring the intersection of large language models and physical manipulation."
baseurl: "/robotics-blog"
url: "https://sheilsarda.github.io"
permalink: /blog/:title/
future: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
